import os
from dotenv import load_dotenv

load_dotenv()

GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")

ASUNCION_CENTER = (-25.2637, -57.5759)

ASUNCION_BOUNDS = {
    "north": -25.16,
    "south": -25.40,
    "west": -57.72,
    "east": -57.55,
}

GREATER_ASUNCION_BOUNDS = {
    "north": -25.10,
    "south": -25.50,
    "west": -57.80,
    "east": -57.45,
}

SEARCH_RADIUS = int(os.getenv("SEARCH_RADIUS", "500"))
GRID_STEP = float(os.getenv("GRID_STEP", "0.005"))

GOOGLE_PLACE_TYPES = {
    "accounting",
    "airport",
    "amusement_park",
    "aquarium",
    "art_gallery",
    "atm",
    "bakery",
    "bank",
    "bar",
    "beauty_salon",
    "bicycle_store",
    "book_store",
    "bowling_alley",
    "bus_station",
    "cafe",
    "campground",
    "car_dealer",
    "car_rental",
    "car_repair",
    "car_wash",
    "casino",
    "cemetery",
    "church",
    "city_hall",
    "clothing_store",
    "convenience_store",
    "courthouse",
    "dentist",
    "department_store",
    "doctor",
    "drugstore",
    "electrician",
    "electronics_store",
    "embassy",
    "finance",
    "fire_station",
    "florist",
    "food",
    "funeral_home",
    "furniture_store",
    "gas_station",
    "general_contractor",
    "grocery_or_supermarket",
    "gym",
    "hair_care",
    "hardware_store",
    "health",
    "hindu_temple",
    "home_goods_store",
    "hospital",
    "insurance_agency",
    "jewelry_store",
    "laundry",
    "lawyer",
    "library",
    "light_rail_station",
    "liquor_store",
    "local_government_office",
    "locksmith",
    "lodging",
    "meal_delivery",
    "meal_takeaway",
    "mosque",
    "movie_rental",
    "movie_theater",
    "moving_company",
    "museum",
    "night_club",
    "painter",
    "park",
    "parking",
    "pet_store",
    "pharmacy",
    "physiotherapist",
    "place_of_worship",
    "plumber",
    "police",
    "post_office",
    "primary_school",
    "real_estate_agency",
    "restaurant",
    "roofing_contractor",
    "rv_park",
    "school",
    "secondary_school",
    "shoe_store",
    "shopping_mall",
    "spa",
    "stadium",
    "storage",
    "store",
    "subway_station",
    "supermarket",
    "synagogue",
    "taxi_stand",
    "tourist_attraction",
    "train_station",
    "transit_station",
    "travel_agency",
    "university",
    "veterinary_care",
    "zoo",
}

META_TYPES = {
    "establishment",
    "point_of_interest",
    "locality",
    "political",
    "sublocality",
    "sublocality_level_1",
    "administrative_area_level_1",
    "administrative_area_level_2",
    "neighborhood",
    "premise",
    "route",
    "street_address",
}

VERTICAL_MAPPING = {
    "Food & Beverage": [
        "restaurant",
        "cafe",
        "bar",
        "bakery",
        "food",
        "meal_delivery",
        "meal_takeaway",
        "liquor_store",
    ],
    "Health & Medical": [
        "hospital",
        "doctor",
        "dentist",
        "pharmacy",
        "drugstore",
        "physiotherapist",
        "veterinary_care",
        "health",
    ],
    "Beauty & Wellness": [
        "beauty_salon",
        "hair_care",
        "spa",
        "gym",
    ],
    "Retail & Shopping": [
        "clothing_store",
        "shoe_store",
        "jewelry_store",
        "electronics_store",
        "furniture_store",
        "home_goods_store",
        "book_store",
        "florist",
        "pet_store",
        "store",
        "shopping_mall",
        "department_store",
        "bicycle_store",
        "hardware_store",
    ],
    "Automotive": [
        "car_dealer",
        "car_rental",
        "car_repair",
        "car_wash",
        "gas_station",
    ],
    "Professional Services": [
        "lawyer",
        "accounting",
        "insurance_agency",
        "real_estate_agency",
        "travel_agency",
    ],
    "Home Services": [
        "electrician",
        "plumber",
        "painter",
        "roofing_contractor",
        "moving_company",
        "locksmith",
        "storage",
        "laundry",
        "general_contractor",
    ],
    "Lodging & Tourism": [
        "lodging",
        "campground",
        "rv_park",
        "tourist_attraction",
        "travel_agency",
    ],
    "Entertainment & Nightlife": [
        "night_club",
        "movie_theater",
        "casino",
        "bowling_alley",
        "amusement_park",
        "stadium",
    ],
    "Education": [
        "school",
        "primary_school",
        "secondary_school",
        "university",
        "library",
    ],
    "Finance": [
        "bank",
        "atm",
        "finance",
    ],
    "Food Retail": [
        "bakery",
        "supermarket",
        "convenience_store",
        "liquor_store",
        "grocery_or_supermarket",
    ],
    "Government & Public": [
        "city_hall",
        "courthouse",
        "police",
        "fire_station",
        "post_office",
        "embassy",
        "local_government_office",
        "cemetery",
    ],
    "Transportation": [
        "airport",
        "bus_station",
        "train_station",
        "subway_station",
        "taxi_stand",
        "transit_station",
        "light_rail_station",
        "parking",
    ],
    "Religious": [
        "church",
        "mosque",
        "synagogue",
        "hindu_temple",
        "place_of_worship",
    ],
    "Arts & Culture": [
        "museum",
        "art_gallery",
        "movie_rental",
    ],
    "Recreation": [
        "park",
        "aquarium",
        "zoo",
    ],
    "Funeral": [
        "funeral_home",
    ],
}

DEFAULT_VERTICAL = "Other"

VERTICAL_NAME_KEYWORDS = {
    "Beauty & Wellness": [
        "peluqueria", "peluquería", "salon", "salón", "belleza", "beleza", "beauty",
        "barber", "barbería", "barberia",
        "spa", "masaje", "masajista", "massage", "wellness",
        "gym", "gimnasio", "fitness", "crossfit", "yoga", "pilates", "polideportivo",
        "nail", "uñas", "unas", "manicure", "pedicure",
        "estetica", "estética", "esteticista", "estilista", "stylist", "facial",
        "maquillaje", "makeup", "make up", "cosmetico", "cosmético",
        "tattoo", "tatuaje", "tatto", "tatoo", "piercing", "ink",
        "pestana", "pestaña", "pestañas", "cejas", "lashes", "brows",
        "depilacion", "depilación", "waxing",
        "studio", "estudio", "academia",
    ],
    "Food & Beverage": [
        "restaurant", "restaurante", "cafe", "café", "cafeteria",
        "bar ", "pub", "cerveceria", "cervecería",
        "pizzeria", "pizzería", "parrilla", "parrillada",
        "bakery", "panaderia", "panadería", "confiteria", "confitería",
    ],
    "Health & Medical": [
        "clinica", "clínica", "clinic", "hospital", "sanatorio",
        "farmacia", "pharmacy", "drogueria", "droguería",
        "doctor", "medico", "médico", "consultorio",
        "dental", "odontolog", "dentista",
        "fisio", "physiotherapy", "rehabilita",
        "veterinar",
    ],
    "Retail & Shopping": [
        "boutique", "tienda", "store", "shop",
    ],
}

NEIGHBORHOODS_ASUNCION = {
    "Centro": (-25.2637, -57.5759),
    "Carmelitas": (-25.2550, -57.5700),
    "Villa Morra": (-25.2480, -57.5650),
    "Mburicá": (-25.2500, -57.5550),
    "Manorá": (-25.2600, -57.5550),
    "Ycuá Satí": (-25.2450, -57.5600),
    "Pyrá": (-25.2380, -57.5530),
    "Recoleta": (-25.2670, -57.5630),
    "San Jorge": (-25.2530, -57.5900),
    "Sajonia": (-25.2700, -57.5850),
    "Chacarita": (-25.2680, -57.6100),
    "Encarnación": (-25.2650, -57.6200),
    "Pettirossi": (-25.2750, -57.6050),
    "Tte. Fariña": (-25.2800, -57.6200),
    "Mcal. López": (-25.2550, -57.5800),
    "Canógrafa": (-25.2750, -57.5750),
    "Loma San Jerónimo": (-25.2710, -57.6400),
    "Santa Ana": (-25.2850, -57.6350),
    "Lambaré (parte)": (-25.3400, -57.6300),
    "Fernando de la Mora (parte)": (-25.3300, -57.5200),
    "San Lorenzo (parte)": (-25.3400, -57.5200),
    "Luque (parte)": (-25.2500, -57.5000),
}

SOCIAL_MEDIA_DOMAINS = [
    "facebook.com",
    "instagram.com",
    "twitter.com",
    "x.com",
    "tiktok.com",
    "wa.me",
    "api.whatsapp.com",
    "web.whatsapp.com",
    "whatsapp.com",
    "youtube.com",
    "linktr.ee",
    "bio.link",
    "beacons.ai",
    "m.me",
]

FREE_WEBSITE_DOMAINS = [
    "wix.com",
    "godaddysites.com",
    "wordpress.com",
    "weebly.com",
    "blogger.com",
    "tumblr.com",
    "sites.google.com",
]
